name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_database: ^9.0.14
  firebase_core: ^1.17.0
  fluttertoast: ^8.0.9
  liquid_progress_indicator: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: DM Serif Text
      fonts:
        - asset: assets/fonts/DMSerifText-Italic.ttf
        - asset: assets/fonts/DMSerifText-Regular.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
